services:
  php:
    build: .
    tty: true
    restart: always
    volumes:
      - ./:/home/chie-box
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/home/chie-box
    depends_on:
      - php
  db:
    build:
      context: .
      dockerfile: postgresql/Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: chiebox
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo # https://github.com/docker-library/postgres/issues/641#issuecomment-869096443
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf

volumes:
  db-data: